# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build the Java service JAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      - uses: actions/upload-artifact@v3
        with:
          name: pi4j-board-info-service
          path: target/pi4j-board-info-service.jar

  deploy:
    name: Deploy to server
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    when: manual
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v2
        with:
          name: pi4j-board-info-service
      - name: List current
        run: |
          ls -la
          ls -la pi4j-board-info-service/
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' scp -o StrictHostKeyChecking=no pi4j-board-info-service.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_ADDRESS }}:${{ secrets.SERVER_LOCATION }}

